"""Rights data: Oklahoma"""
DATA = [
("OK","domestic_violence","Protective orders (VPO) within 14 days, emergency ex parte orders same day. Address Confidentiality Program through AG. Right to be present at all proceedings. Victim advocate provided.","Felony DV: 5yr. Misdemeanor: 1yr. No limit if strangulation.","Healthcare workers must report injuries from criminal activity. Law enforcement must provide DV resource info at scene.","OK Crime Victims Compensation Board up to $20K. Restitution mandatory at sentencing."),
("OK","assault","Right to be informed of all proceedings, present at trial, heard at sentencing. Victim impact statements. Notification of offender release.","Felony: 5yr. Misdemeanor: 1yr. Aggravated: 7yr.","Healthcare providers report injuries from violence.","OK CVC covers medical, counseling, lost wages up to $20K. Restitution ordered at sentencing."),
("OK","theft","Restitution ordered upon conviction. Right to return of stolen property held as evidence once no longer needed.","Felony: 5yr. Misdemeanor: 1yr.","None specific.","Full restitution ordered on conviction."),
("OK","fraud","AG Consumer Protection Unit. Oklahoma Consumer Protection Act allows actual damages plus attorney fees.","Most fraud: 5yr. Insurance fraud: 5yr from discovery.","Insurance companies report suspected fraud to AG.","Restitution ordered. Civil remedies under Oklahoma Consumer Protection Act."),
("OK","stalking","Protective orders. Stalking is a felony on second offense. GPS monitoring available. Cyberstalking covered under statute.","Felony: 5yr. Misdemeanor: 1yr.","None specific.","Restitution for security measures, relocation, counseling. OK CVC eligible."),
("OK","sexual_assault","Free forensic exam (SANE), no police report required. Rape shield law. Victim advocate at exam and proceedings. Right to not be questioned about prior sexual history.","No statute of limitations for rape and first-degree sexual abuse since 2016. Child victims: no limit.","Healthcare professionals must report. ALL adults must report child sexual abuse.","OK CVC up to $20K. Mandatory restitution. Covers medical, counseling, forensic exam costs."),
("OK","child_abuse","Mandatory reporters: teachers, doctors, nurses, counselors, law enforcement, childcare workers. DHS investigation within 24hrs for emergency, 5 days otherwise. CASA advocates appointed.","No statute of limitations for child sexual abuse. Physical abuse felony: 5yr.","Mandatory reporters must report within 24hrs. Failure is a misdemeanor.","Full restitution. OK CVC for child victims. DHS services provided."),
]